// Generated by Supabase MCP `generate_typescript_types`. Regenerate with:
//   mcp__ca3fa622-..._generate_typescript_types
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      research_citations: {
        Row: {
          excerpt: string | null
          favicon_url: string | null
          id: string
          ordinal: number
          source_domain: string | null
          source_url: string
          title: string | null
          turn_id: string
        }
        Insert: {
          excerpt?: string | null
          favicon_url?: string | null
          id?: string
          ordinal?: number
          source_domain?: string | null
          source_url: string
          title?: string | null
          turn_id: string
        }
        Update: {
          excerpt?: string | null
          favicon_url?: string | null
          id?: string
          ordinal?: number
          source_domain?: string | null
          source_url?: string
          title?: string | null
          turn_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "research_citations_turn_id_fkey"
            columns: ["turn_id"]
            isOneToOne: false
            referencedRelation: "research_turns"
            referencedColumns: ["id"]
          },
        ]
      }
      research_runs: {
        Row: {
          coral_session_id: string | null
          error_message: string | null
          finished_at: string | null
          id: string
          model_usage: Json
          session_id: string
          started_at: string
          status: Database["public"]["Enums"]["run_status"]
          trigger_turn_id: string | null
        }
        Insert: {
          coral_session_id?: string | null
          error_message?: string | null
          finished_at?: string | null
          id?: string
          model_usage?: Json
          session_id: string
          started_at?: string
          status?: Database["public"]["Enums"]["run_status"]
          trigger_turn_id?: string | null
        }
        Update: {
          coral_session_id?: string | null
          error_message?: string | null
          finished_at?: string | null
          id?: string
          model_usage?: Json
          session_id?: string
          started_at?: string
          status?: Database["public"]["Enums"]["run_status"]
          trigger_turn_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "research_runs_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "research_sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "research_runs_trigger_turn_id_fkey"
            columns: ["trigger_turn_id"]
            isOneToOne: false
            referencedRelation: "research_turns"
            referencedColumns: ["id"]
          },
        ]
      }
      research_sessions: {
        Row: {
          anchor_type: Database["public"]["Enums"]["anchor_type"]
          anchor_value: string | null
          archived_at: string | null
          created_at: string
          id: string
          slug: string
          title: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          anchor_type: Database["public"]["Enums"]["anchor_type"]
          anchor_value?: string | null
          archived_at?: string | null
          created_at?: string
          id?: string
          slug: string
          title?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          anchor_type?: Database["public"]["Enums"]["anchor_type"]
          anchor_value?: string | null
          archived_at?: string | null
          created_at?: string
          id?: string
          slug?: string
          title?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "research_sessions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["privy_user_id"]
          },
        ]
      }
      research_turns: {
        Row: {
          agent_name: string | null
          content: string
          created_at: string
          id: string
          parent_turn_id: string | null
          parts: Json | null
          role: Database["public"]["Enums"]["turn_role"]
          run_id: string | null
          session_id: string
          status: Database["public"]["Enums"]["turn_status"]
        }
        Insert: {
          agent_name?: string | null
          content?: string
          created_at?: string
          id?: string
          parent_turn_id?: string | null
          parts?: Json | null
          role: Database["public"]["Enums"]["turn_role"]
          run_id?: string | null
          session_id: string
          status?: Database["public"]["Enums"]["turn_status"]
        }
        Update: {
          agent_name?: string | null
          content?: string
          created_at?: string
          id?: string
          parent_turn_id?: string | null
          parts?: Json | null
          role?: Database["public"]["Enums"]["turn_role"]
          run_id?: string | null
          session_id?: string
          status?: Database["public"]["Enums"]["turn_status"]
        }
        Relationships: [
          {
            foreignKeyName: "research_turns_parent_turn_id_fkey"
            columns: ["parent_turn_id"]
            isOneToOne: false
            referencedRelation: "research_turns"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "research_turns_run_id_fkey"
            columns: ["run_id"]
            isOneToOne: false
            referencedRelation: "research_runs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "research_turns_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "research_sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      user_settings: {
        Row: {
          openrouter_api_key_encrypted: string | null
          openrouter_api_key_set_at: string | null
          subscription_tier: string
          updated_at: string
          user_id: string
        }
        Insert: {
          openrouter_api_key_encrypted?: string | null
          openrouter_api_key_set_at?: string | null
          subscription_tier?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          openrouter_api_key_encrypted?: string | null
          openrouter_api_key_set_at?: string | null
          subscription_tier?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_settings_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["privy_user_id"]
          },
        ]
      }
      users: {
        Row: {
          created_at: string
          display_name: string | null
          email: string | null
          privy_user_id: string
          solana_address: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          display_name?: string | null
          email?: string | null
          privy_user_id: string
          solana_address?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          display_name?: string | null
          email?: string | null
          privy_user_id?: string
          solana_address?: string | null
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      user_settings_public: {
        Row: {
          openrouter_api_key_set: boolean | null
          openrouter_api_key_set_at: string | null
          subscription_tier: string | null
          updated_at: string | null
          user_id: string | null
        }
        Insert: {
          openrouter_api_key_set?: never
          openrouter_api_key_set_at?: string | null
          subscription_tier?: string | null
          updated_at?: string | null
          user_id?: string | null
        }
        Update: {
          openrouter_api_key_set?: never
          openrouter_api_key_set_at?: string | null
          subscription_tier?: string | null
          updated_at?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "user_settings_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["privy_user_id"]
          },
        ]
      }
    }
    Functions: {
      clear_openrouter_key: { Args: never; Returns: undefined }
      current_privy_user_id: { Args: never; Returns: string }
      get_openrouter_key: { Args: { p_user_id: string }; Returns: string }
      set_openrouter_key: { Args: { plaintext: string }; Returns: undefined }
    }
    Enums: {
      anchor_type:
        | "asset"
        | "protocol"
        | "story"
        | "wallet"
        | "topic"
        | "freeform"
      run_status: "queued" | "running" | "complete" | "failed" | "cancelled"
      turn_role:
        | "user"
        | "orchestrator"
        | "specialist"
        | "synthesizer"
        | "assistant"
      turn_status: "pending" | "streaming" | "complete" | "error"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      anchor_type: [
        "asset",
        "protocol",
        "story",
        "wallet",
        "topic",
        "freeform",
      ],
      run_status: ["queued", "running", "complete", "failed", "cancelled"],
      turn_role: [
        "user",
        "orchestrator",
        "specialist",
        "synthesizer",
        "assistant",
      ],
      turn_status: ["pending", "streaming", "complete", "error"],
    },
  },
} as const
