-- Cost telemetry on archived fleet runs.
--
-- Per-agent LLM token usage (model, input/output tokens, call count),
-- captured by the fleet-gateway from coral `llm_proxy_call` events and stored
-- as a JSON blob. Lives HERE — the durable, all-runs substrate the dream pass
-- reads — in addition to research_runs.model_usage (the chat-side mirror,
-- which only exists for chat-dispatched runs).
--
-- Shape (matches the gateway's buildModelUsage output):
--   { "agents": { "<name>": { "model", "input_tokens", "output_tokens", "calls" } },
--     "totals": { "input_tokens", "output_tokens", "calls" },
--     "estimated_usd": null }
ALTER TABLE fleet_runs_archive ADD COLUMN model_usage TEXT;
